=== kuang2315534042/test/UserDemo2/bin/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (datasource, sqlinfo)>
<!ELEMENT datasource (property)*>
<!ELEMENT sqlinfo (select*, update*)>

<!ATTLIST datasource class CDATA #REQUIRED>
<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #IMPLIED>
<!ATTLIST property value CDATA #IMPLIED>


<!ELEMENT select (#PCDATA)>
<!ATTLIST select id ID #REQUIRED>
<!ATTLIST select resultType CDATA #IMPLIED>
<!ATTLIST select parameterType CDATA #IMPLIED>

<!ELEMENT update (#PCDATA)>
<!ATTLIST update id ID #REQUIRED>
<!ATTLIST update resultType CDATA #IMPLIED>
<!ATTLIST update parameterType CDATA #IMPLIED>

=== kuang2315534042/test/UserDemo2/bin/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM 'config.dtd'>
<configuration>
	<datasource class="com.mchange.v2.c3p0.ComboPooledDataSource">
		<property name="driverClass" value="com.mysql.jdbc.Driver"/>
		<property name="jdbcUrl" value="jdbc:mysql://localhost:3306/db_user"/>
		<property name="user" value="root"/>
		<property name="password" value="root"/>
	</datasource>
	
	<sqlinfo>
		<select id="selectAll"  resultType="com.apps.pojo.User">
			select * from tb_user
		</select>
		
		<select id="selectById"  resultType="com.apps.pojo.User">
			select * from tb_user where uid=?
		</select>
		
		<select id="selectUsersByUnameAndAddr"  resultType="com.apps.pojo.User">
			select * from tb_user where uname like concat('%', ?, '%') and address like concat('%', ?, '%')
		</select>
	
		<update id="deleteUser">
			delete from tb_user where uid=?
		</update>
		
		<update id="insertUser" parameterType="com.apps.pojo.User">
			insert into tb_user(uname, address, age) values(#{uname}, #{address}, #{age})
		</update>
		
		<update id="updateUser" parameterType="com.apps.pojo.User">
			update tb_user set uname=#{uname}, age=#{age}, address=#{address} where uid=#{uid}
		</update>
		
	</sqlinfo>
	
</configuration>
